# Generated by Django 4.2 on 2023-04-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=20)),
                ('category_name', models.CharField(max_length=20)),
                ('position', models.PositiveSmallIntegerField(unique=True)),
                ('photo', models.ImageField(upload_to='projects_photo')),
            ],
        ),
    ]
