# Generated by Django 4.2 on 2023-04-20 17:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_projectcategory_options_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number is waited in format +380xx xxx xx xx', regex='^+?3?8?0?\\d{2}[- ]?(\\d[- ]?){7}$')])),
                ('message', models.TextField(blank=True, max_length=500)),
                ('is_processed', models.BooleanField(default=False)),
                ('date_request', models.DateTimeField(auto_now_add=True)),
                ('date_response', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-date_request',),
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('position',), 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'ordering': ('position',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='main_app.projectcategory'),
        ),
    ]
